on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Merge master branch
      run: "git merge origin/master"
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@localhost
      if: github.ref != 'refs/heads/master'
    - name: Install TiddlyWiki
      run: "npm install ento/TiddlyWiki5#jasmine-3 --no-save"
    - name: Run tests
      run: "./node_modules/.bin/tiddlywiki test"
  pages:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: docker://elasticdog/tiddlywiki:5.1.19
      with:
        args: src --build index
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: index.html
        path: src/output/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./src/output
      with:
        emptyCommits: false
      if: github.ref == 'refs/heads/master'
